### ISSUE TITLE
Order of javascript files

### ISSUE THREAD

**Issue by rickyngk** [stephenplusplus/grunt-wiredep#133]
I use onsenUI that has already used AngularJS and jqLite. Then need to add jquery, onsenUI asked me to add jquery AFTER AngularJS, but for grunt-wiredep, jquery always on top

**Comment by stephenplusplus** [comment]
The problem is likely due to the "elite dependencies" hidden behavior of wiredep. In the early Bower days, many packages were registering without properly listing their dependencies. So for the end user, it was safe to assume if `jQuery` was in their project's bower.json, it was going to need to be the first dependency when injected. Now that time has passed, we have more reliable packages in Bower. We're working on https://github.com/taptapship/wiredep/pull/118 getting rid of this behavior.

**Comment by rickyngk** [comment]
yes, now I use excludes, and add jquey & angularjs manually in order.
